version: '3.8'
services:
  postgres-db:
    image: postgres:15.3
    container_name: ecommerce
    restart: 'no'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'ecommerce_db'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
